# Generated by Django 5.0.1 on 2024-01-18 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0003_team_team_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='team',
            old_name='team_image',
            new_name='image',
        ),
    ]
