# Generated by Django 5.0.1 on 2024-01-15 17:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0001_initial'),
        ('users', '0002_user_join_date_user_manager_user_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='softwares',
            field=models.ManyToManyField(related_name='users', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='user',
            name='team',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='team_members', to='teams.team'),
        ),
    ]
