# Generated by Django 5.0.1 on 2024-01-16 11:16

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_softwares_user_team'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='softwares',
            field=models.ManyToManyField(null=True, related_name='users', to=settings.AUTH_USER_MODEL),
        ),
    ]
