# Generated by Django 5.0.1 on 2024-01-16 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('softwares', '0004_remove_software_users'),
        ('users', '0004_alter_user_softwares'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='softwares',
            field=models.ManyToManyField(null=True, related_name='users', to='softwares.software'),
        ),
    ]
