# Generated by Django 5.0.1 on 2024-01-18 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hardwares', '0002_hardware_type'),
        ('users', '0005_alter_user_softwares'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='hardwares',
            field=models.ManyToManyField(null=True, related_name='users', to='hardwares.hardware'),
        ),
    ]
