# Generated by Django 5.0.1 on 2024-01-18 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_user_profile_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='profile_image',
            new_name='image',
        ),
    ]
