# Generated by Django 5.0.1 on 2024-01-16 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('softwares', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='software',
            name='licence_cost',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
