# Generated by Django 5.0.1 on 2024-01-16 12:13

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('softwares', '0002_software_licence_cost'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='software',
            name='users',
            field=models.ManyToManyField(related_name='softwares_subscribed', to=settings.AUTH_USER_MODEL),
        ),
    ]
