# Generated by Django 5.0.1 on 2024-01-18 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hardwares', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hardware',
            name='type',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
